### PR TITLE
PR with prow

### PR DESCRIPTION
**Pull request by skhedim**
What can I say ?

### CODE REVIEW

**Comment by skhedim** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **skhedim**

If they are not already assigned, you can assign the PR to them by writing `/assign @skhedim` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=skhedim%2Fjx-prow).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/skhedim/jx-prow/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by skhedim** [comment]
:star: PR built and available in a preview environment **skhedim-jx-prow-pr-1** [here](http://jx-prow.jx-serverless-skhedim-jx-prow-pr-1.serverless.34.90.4.38.nip.io)

**Comment by skhedim** [comment]
/assign
coucou

**Comment by skhedim** [comment]
@skhedim: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/skhedim/jx-prow/pull/1#issuecomment-512270382):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by xyzopowa** [comment]
/approve
pouet

**Comment by skhedim** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/skhedim/jx-prow/pull/1#issuecomment-512274958" title="Approved">xyzopowa</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=skhedim%2Fjx-prow).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/skhedim/jx-prow/blob/master/OWNERS)~~ [xyzopowa]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by skhedim** [comment]
:star: PR built and available in a preview environment **skhedim-jx-prow-pr-1** [here](http://jx-prow.jx-serverless-skhedim-jx-prow-pr-1.serverless.34.90.4.38.nip.io)

**Pull request merged**
